version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tony-g-yt"
s3_bucket = "jvb-code"
s3_prefix = "SAM/tony-g-yt"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""
image_repositories = []