AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Steal intellectual property from Tony Fantano'

Parameters:
  Debug:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

Globals:
  Function:
    Timeout: 120
    MemorySize: 128
    Environment:
      Variables:
        DEBUG: !Ref Debug
        # GOOGLE_SEARCH_DISABLED: undefined

# https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html#golang-package-create-sam
Resources:
  YoutubeLambdaFn:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Runtime: provided.al2023
      CodeUri: lambdas/youtube/
      Handler: bootstrap
      Architectures:
        - arm64
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            # TODO: does prefix* work? Or will I need to add one policy per parameter?
            # Seems to work!
            ParameterName: /Tony2Stack/*
      Events:
        WeeklyInvoko:
          Type: ScheduleV2
          Properties:
            # also accepts '{ "videoIds": []string] }' but defaults to next 5 videos
            Input: '{}'
            # TODO: on cron, tuesday morning
            # Tony releases weekly track roundups on Monday I think.
            # https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-scheduled-rule-pattern.html
            # minutes, hours, day-of-month, month, day-of-week, year
            ScheduleExpression: cron(0 7 ? * TUE *)

Outputs:
  YoutubeLambdaFn:
    Description: Youtube video descriptions to youtube playlists
    Value: !Ref YoutubeLambdaFn
